export const catagoryList = [
  "Mental status examination",
  "Cranial nerve examination",
  "Motor system",
  "Deep tendon reflexes",
  "Sensation",
  "Cerebellum",
];

export const testList = [
  "The assessment of consciousness, often using the Glasgow Coma Scale (GCS)",
  "Mental status examination, often including the abbreviated mental test score (AMTS) or mini mental state examination (MMSE)",
  "Global assessment of higher functions",
  "Intracranial pressure is roughly estimated by fundoscopy; this also enables assessment for microvascular disease",
  "Cranial nerves (I-XII)",
  "sense of smell (I)",
  " visual fields and acuity (II)",
  "eye movements (III, IV, VI) and pupils (III, sympathetic and parasympathetic)",
  "sensory function of face (V)",
  " strength of facial (VII) and shoulder girdle muscles (XI)",
  "hearing (VII, VIII)",
  "taste (VII, IX, X)",
  "pharyngeal movement and reflex (IX, X)",
  "tongue movements (XII)",
  "Muscle strength, often graded on the MRC scale 0 to 5[4] (i.e., 0 = Complete Paralysis to 5 = Normal Power)",
  "grades 4−, 4 and 4+ maybe used to indicate movement against slight",
  " moderate and strong resistance respectively",
  "Muscle tone and signs of rigidity",
  "Examination of posture",
  "Decerebrate",
  "Decorticate",
  "Hemiparetic",
  "Resting tremors",
  "Abnormal movements",
  "Seizure",
  "Fasciculations",
  "Tone",
  "Spasticity",
  "Pronator drift",
  "Rigidity",
  "Cogwheeling (abnormal tone suggestive of Parkinson's disease)",
  "Gegenhalten – is resistance to passive change, where the strength of antagonist muscles increases with increasing examiner force. More common in dementia",
  "Reflexes: masseter",
  "biceps and triceps tendon",
  "knee tendon",
  "ankle jerk and plantar (i.e., Babinski sign)",
  "Globally, brisk reflexes suggest an abnormality of the UMN or pyramidal tract, while decreased reflexes suggest abnormality in the anterior horn, LMN, nerve or motor end plate. A reflex hammer is used for this testing",
  "Sensory system testing involves provoking sensations of fine touch, pain and temperature. Fine touch can be evaluated with a monofilament test, touching various dermatomes with a nylon monofilament to detect any subjective absence of touch perception",
  "Sensory",
  "Light touch",
  "Pain",
  "Temperature",
  "Vibration",
  "Position sense",
  "Graphesthesia",
  "Stereognosis, and Two-point discrimination (for discriminative sense)",
  "Extinction",
  "Romberg test – 2 out of the following 3 must be intact to maintain balance: i. vision ii. vestibulocochlear system iii. epicritic sensation",
  "Cerebellar testing",
  "Dysmetria",
  "Finger-to-nose test",
  "Ankle-over-tibia test",
  "Dysdiadochokinesis",
  "Rapid pronation-supination",
  "Ataxia",
  "Assessment of gait",
  "Nystagmus",
  "Intention tremor",
  "Staccato speech.",
];
