export const testNameList = [
  "Select",
  "amniocentesis",
  "blood analysis",
  "gastric fluid analysis",
  "kidney function test",
  "liver function test",
  "lumbar puncture",
  "malabsorption test",
  "Pap smear",
  "phenolsulfonphthalein test",
  "pregnancy test",
  "prenatal testing",
  "protein-bound iodine test",
  "angiocardiography",
  "angiography",
  "brain scanning",
  "cholecystography",
  "myelography",
  "tomography",
  "complementation test",
  " fluorescence in situ hybridization",
  "preimplantation genetic diagnosis",
];

export const Specification = [
  "Select",
  "value1",
  "value2",
  "value3",
  "value4",
  "value5",
  "value6",
];

export const frequencyList = [
  "Select",
  "DAILY",
  " 2 TIMES A WEEK",
  "2 TIMES DAILY",
  "3 TIMES A WEEK",
  "3 TIMES DAILY",
  "4 TIMES A WEEK",
  "4 TIMES DAILY",
  "AS DIRECTED",
  "AS NEEDED",
  "BED TIME",
  "EVERY 12 HOURS",
  "EVERY 2 HOURS",
  "EVERY 4 HOURS",
  "EVERY 6 HOURS",
  "EVERY 72 HOURS",
  "EVERY 8 HOURS",
  "EVERY AM",
  "EVERY OTHER DAY",
  "EVERY OTHER WEEK",
  "EVERY PM",
  "HOURLY",
  "ENTERMITTENT",
  "MONTHLY",
  "WEEKLY",
  "O2- CONTINUOUS",
  "O2- NIGHTLY",
  "O2- PRN",
];

export const medicineNameList = [
  "Select",
  "Brufen 400 Tablet",
  "Brilinta 90mg Tablet",
  "Azax 500 Tablet",
  "Aldactone Tablet",
  "Axcer  90mg Tablet",
  "Azoran Tablet",
  "Betadine 10% Solution",
  "Betnesol Tablet",
  "Alfoo 10mg Tablet PR",
  "Amaryl 1mg Tablet",
  "AB Phylline Capsule",
  "Almox 500 Capsule",
  "Calpol 500mg Tablet",
  "Ceftum 500mg Tablet",
  "Cyra-D Capsule",
  "Clexane 40mg Injection",
  "Cetrizine Tablet",
  "Concor 5 Tablet",
  "Clexane 60mg Injection",
  "Clindac A 1% Gel",
  "Doxt-SL Capsule",
  "Defcort 6 Tablet",
  "Diamox Tablet",
  "Deplatt A 75 Tablet",
  "Doxolin 400mg Tablet",
  "Bilasure M 20mg/10mg Tablet",
  "Betacap Plus 10 Capsule SR",
  "Benzac AC 5% Gel",
  "Bupron XL 150 Tablet",
  "Emanzen-D Tablet",
  "Eliwel 10mg Tablet",
  "Etizola 0.5 Tablet",
  "Eltroxin 25mcg Tablet",
  "Cipladine Ointment",
  "Cepodem XP 325 Tablet",
  "Cardivas 3.125 Tablet",
  "Cabgolin 0.5 Tablet",
  "Ceftas 200 Tablet",
  "Crina-NCR 10mg Tablet",
  "Ciplox D Eye/Ear Drops",
  "Cardace 2.5 Tablet",
  "Codistar-DX Cough Syrup",
  "CTD 6.25 Tablet",
  "Grilinctus  Syrup",
  "Glycomet-GP 1 Tablet PR",
  "Glycomet-GP 2 Tablet PR",
  "Galvus Met 50mg/500mg Tablet",
  "Glycomet Trio 2 Tablet SR",
  "Glycomet 1gm Tablet",
  "Fabiflu Tablet",
  "Flavedon MR Tablet",
  "Fluguard Tablet",
  "Darolac Sachet",
  "Brimolol Eye Drop",
  "Betnesol Oral Drops",
  "Basalog 100IU/ml Refill Cartridge",
  "Budesal 0.5mg Respules 2ml",
  "Headset Tablet",
  "Hyponat-O 15 Tablet",
  "HCQS 400 Tablet",
  "Hepamerz Granules",
  "Hatric 3 Tablet",
];

export const restriction = [
  "NO CONCENTRATED SWEETS",
  "NPO",
  "PEG TUBE",
  "PUREED",
  "PUREED NO ADDED SALT",
  "REGULAR DIET",
  "DIABETIC DIET",
  "ENSURE SUPPLEMENT",
  "FLUID RESTRICTED DIET",
  "FULL LIQUID",
  "GLEUCERNIA SUPPLEMENT 1 CAN 1X DAY AND 1 CAN PRN MISSED MEALS",
  "HEART HEALTHY",
  "HIGH FIBER",
  "AVOID CONCENTRATED SWEETS",
  "CARDIAC DIET",
  "CHOPPED MEAT",
  "CONSISTENT CARBOHYDRATE",
  "CONSISTENT CARBOHYDRATE",
  "HIGH FIBER",
  "HONEY THICKENED LIQUIDS",
  "ISOSOURCE",
  "LIBERALIZED DIABETIS",
  "NAS",
  "NO ORANGES,BANANAS,ORANGE JUICE,MELONS,TOMATOES",
  "LIMIT VIT K",
  "LOW CHOLESTEROL",
  "LOW FAT",
  "LOW SODIUM",
  "MECHANICAL SOFT",
  "NECTAR THICK LIQUIDS",
  "NO CARBS",
  "REGULAR NO ADDED FAT",
  "REGULAR NO ADDED SALT",
  "RENAL DIET",
  "RENAL DIET",
  "THIN LIQUIDS",
  "TWOCAL PER PEG TUBE",
  "Others",
];
export const pEducation = [
  "Weight loss",
  "Exercise 45-60 min 4-5/wk",
  "EIOH cessation",
  "smoking cessation",
  "Low fat,low salt,low cholesterol diet",
  "Diabetes",
  "No driving or no activity requiring mental aiemess while on _____",
  "Increase oral fluid",
  "No heavy lifting",
  "Plan of care explained to the patient",
  "RTC or go to ED if signs/symptoms worsens _____ Total time face to face ______ minutes >50% conseling/coordination of care",
  "Others",
];
export const precautionList = [
  "SHARPS CONTAINERS",
  "SMOKING IN HOME",
  "SOILED/UNHYGENIC LIVING CONDITIONS",
  "STANDARD PRECAUTIONS",
  "UNIVERSAL PRECAUTIONS",
  "INFECTION PRECAUTIONS",
  "FALL PRECAUTIONS",
  " CLERA PATHWAYS",
  "MEDICATION PRECAUTIONS",
  "SAFEETY PRECAUTIONS",
  "EMERGENCY PLAN",
  "UNSAFE FLOORING",
  "CLUTTERED ENVIRONMENT",
  "CONTACT PRECAUTIONS",
  "COVID PRECAUTIONS",
  "DEMENTIA",
  "DEMETIA WITH WANDERING",
  "DEPRESSIVE DISORDER PRECAUTIONS",
  "DIABETIC PRECAUTIONS",
  "EMERGENCY PLAN",
  "EMERGENCY PRECAUTIONS",
  "FALL PRECAUTIONS",
  "HONEY THICKEND LIQUIDS",
  "INADEQUATE LIGHTING",
  "INDOOR PET",
  "INFECTION PRECAUTION",
  "INSECTS/RODENTS",
  "JOINT PRECAUTIONS",
  "LONG TERM ANTICOAGULATION",
  "Others",
];
